#These db properties are optional for H2 embedded database
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: murugan
      password: murugan

server:
  port: 8002
  
  